FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm config set registry https://registry.npmjs.org/
RUN npm install

COPY . .

ENV NODE_ENV=production

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]